<?php
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

// Authentication Routes (generated by Laravel auth)
Auth::routes();

// Product Management Routes
Route::middleware(['auth'])->prefix('products')->name('products.')
->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
    Route::post('/products-store', [ProductController::class, 'store'])->name('store');
    Route::get('/show/{id}', [ProductController::class, 'show'])->name('show');
    Route::put('/update/{id}', [ProductController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy');

});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
